services:

  # PostgreSQL Service
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Resumiendo69
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  
  # MongoDB Service
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Resumiendo69
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data      

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672 # RabbitMQ
      - 15672:15672 # RabbitMQ Management Web Browser


# Auction Service
  auction-svc:
    image: spinalsubset69/auction-svc:latest
    build: 
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres:5432; User Id=postgres; Password=Resumiendo69; Database=auctions;
      - IdentityServiceUrl=http://identity-svc
    ports:
      - 7001:80
    depends_on:
      - postgres
      - rabbitmq

# Search Service
  search-svc:
    image: spinalsubset69/search-svc:latest
    build: 
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://root:Resumiendo69@mongodb
      - AuctionServiceUrl=http://auction-svc
    ports:
      - 7002:80
    depends_on:
      - mongodb
      - rabbitmq

# Idenitty Service
  identity-svc:
    image: spinalsubset69/identity-svc:latest
    build: 
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80      
      - ConnectionStrings__DefaultConnection=Server=postgres:5432; User Id=postgres; Password=Resumiendo69; Database=identity;
    ports:
      - 5000:80
    depends_on:
      - postgres

# Gateway Service
  gateway-svc:
    image: spinalsubset69/gateway-svc:latest
    build: 
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80            
    ports:
      - 6001:80    